# Generated by Django 3.0.8 on 2020-08-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suggestion',
            new_name='Review',
        ),
    ]
